site:
  title: eProcurement Ontology
  start_page: EPO::index.adoc
content:
  edit_url: false
  sources:
    - url: https://github.com/OP-TED/ePO.git
      branches:
      - master
      start_path: ascii_doc
ui:
  bundle:
    url: https://github.com/OP-TED/antora-eui/releases/download/ui-bundle/master/ui-bundle.zip
    snapshot: true
  supplemental_files: ./ascii_doc/supplemental-ui